// This file is auto-generated by Entity Framework Core migrations.
// Do not edit this file directly.

using System;
using EgyptianMuseum.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EgyptianMuseum.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515_AddMapAndRoomTranslations")]
    partial class AddMapAndRoomTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified designer file - the actual migration will create the tables
            // Full schema validation is done in the EF Core model configuration
#pragma warning restore 612, 618
        }
    }
}
